### ISSUE TITLE
Setup of daemon on device

### ISSUE THREAD

**Issue by dphroon** [idatum/labrfcat#1]
Wow this is great!
I've been playing with my Yardstick One for a while now, just haven't got around to finally doing something like this. I have fans from a different manufacturer so still working on the codes.

How did you setup the device that runs the daemon? OS? just rflib? which python version? My final concept is to put it in a docker file

**Comment by idatum** [comment]
@dphroon  -- I haven't moved it to Docker yet, mainly because I had trouble with the fact that the Yardstick One device is a link:
`/dev/RFCAT3 -> bus/usb/002/007`
I couldn't get Docker to correctly handle permissions, etc. I meant to spend more time on figuring that out; it's on my list.
So for now I just run it as a systemd unit:
`cat /etc/systemd/system/minkad.service
[Unit]
Description=Lab rfcat Minka Aire control

[Service]
Type=simple
User=rfcat
ExecStart=/home/rfcat/bin/labrfcat/minkad.sh

[Install]
WantedBy=multi-user.target`

I'll include docker-compose.yaml once I get it running under Docker.

**Comment by idatum** [comment]
Python 3.9 and rflib on  Debian 11.
